### ISSUE TITLE
Ephemeral services that start quickly [for PR reviews etc]

### ISSUE THREAD

**Issue by 46bit** [alphagov/paas-roadmap#59] opened 2020-03-23 17:21 UTC
Several tenants are spinning up their services for every Github Pull Request in progress, so that the work can be previewed by a reviewer.

A key need for that work is that the review apps come up quickly. Including their backing services.

It's already possible to deploy fast-starting databases to PaaS with ephemeral disk storage, but their credentials won't automatically go into VCAP_SERVICES and they have to be deployed in a different way.

The PaaS team previously discussed this and weren't keen to complicate our service brokers further. However there is an important need here and we didn't think things through enough.

**Comment by richardTowers** [comment] 2020-03-27 10:43
GOV.UK Pay's approach to this is interesting.

In staging / prod we use a postgres database from the service broker. We use the [env-map buildpack](https://github.com/alphagov/env-map-buildpack/) to pluck credentials out of the VCAP_SERVICES environment variable before the apps start.

In dev environments, we push a docker-image postgres, but we also create a user-provided service containing credentials in the same format as the service-brokered database. This means the application can be exactly the same in development as production - it binds to a service and uses the credentials it finds to connect to a DB.

CloudFoundry terraform describing our setup here: https://github.com/alphagov/pay-omnibus/blob/develop/terraform/modules/paas-stub-postgres/postgres.tf

(@nusnewob - might be relevant to your interests)

**Comment by saliceti** [comment] 2020-05-26 09:14
This would be an important feature for many of our teams.
@richardTowers works but it makes dev set-up not consistent with other environments.
Maybe a broker providing ephemeral instances, such as https://github.com/cloudfoundry-community/cf-containers-broker .

**Comment by saliceti** [comment] 2020-06-29 14:44
Hi. This feature would be important. Why has it been archived from the roadmap?

**Comment by emilygds** [comment] 2020-07-01 14:55
Hi Colin. We have merged it with another issue about making CI/CD easier in general: https://github.com/alphagov/paas-roadmap/issues/20 We wanted to group all the issues relating to CI/CD workflows to make it easier for us to tackle them. Thanks for the feedback that solving the ephemeral services part of the problem is important.

**Comment by wryobservations** [comment] 2022-08-09 12:37
Hello, as you are hopefully aware, GDS is [retiring GOV.UK PaaS](https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/) by end 2023. Our focus now is maintaining the platform throughout the decommissioning process with our usual levels of security, support and availability, and any enhancements are focussed on optimising this and helping tenants migrate away. Hence we are closing issues raised that don't meet these criteria. Thanks for understanding.

**Closed by wryobservations** 2022-08-09 12:37 UTC
