### ISSUE TITLE
Accessibility compliance discovery

### ISSUE THREAD

**Issue by emilygds** [alphagov/paas-roadmap#39] opened 2020-02-18 11:24 UTC
GOV.UK PaaS complies with the [accessibility regulations](https://www.gov.uk/guidance/accessibility-requirements-for-public-sector-websites-and-apps).

**Comment by pauldougan** [comment] 2020-08-25 12:21
this is a duplicate of #47

**Closed by pauldougan** 2020-08-25 12:21 UTC
